const mongoose = require('mongoose');

// --- Sub-schemas for nested medical information ---
// These are not separate collections, but arrays of objects within a Patient document.

const SymptomSchema = new mongoose.Schema({
  id: { type: String, required: true }, // Generated by backend: `symp_${Date.now()}`
  description: { type: String, required: true },
  date: { type: Date, required: true },
  severity: { type: String, enum: ['Mild', 'Moderate', 'Severe'], default: 'Mild' },
}, { _id: false }); // Prevents Mongoose from adding its own _id to subdocuments

const DiagnosisSchema = new mongoose.Schema({
  id: { type: String, required: true }, // Generated by backend: `diag_${Date.now()}`
  condition: { type: String, required: true },
  date: { type: Date, required: true },
  notes: { type: String },
}, { _id: false });

const PrescriptionSchema = new mongoose.Schema({
  id: { type: String, required: true }, // Generated by backend: `pres_${Date.now()}`
  medication: { type: String, required: true },
  dosage: { type: String },
  startDate: { type: Date, required: true },
  endDate: { type: Date },
}, { _id: false });

const BillSchema = new mongoose.Schema({
  id: { type: String, required: true }, // Generated by backend: `bill_${Date.now()}`
  item: { type: String, required: true }, // Matches frontend 'item'
  bill: { type: Number, required: true }, // Matches frontend 'bill'
  date: { type: Date, required: true },
  status: { type: String, enum: ['Unpaid', 'Paid'], default: 'Unpaid' },
}, { _id: false });

// --- Main Patient Schema ---
const PatientSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  dateOfBirth: { type: Date, required: true },
  gender: { type: String, required: true },
  emailOrMobile: { type: String, required: true, unique: true },
  contactNumber: { type: String, required: true },
  address: { type: String, required: true },
  medicalHistory: { type: String },

  // Nested arrays for medical information
  symptoms: [SymptomSchema],
  diagnoses: [DiagnosisSchema],
  prescriptions: [PrescriptionSchema],
  bills: [BillSchema],
}, {
  timestamps: true // Adds createdAt and updatedAt fields automatically
});

module.exports = mongoose.models.Patient || mongoose.model('Patient', PatientSchema);
